[app]
name = "Echt-A-Sketch"
category = "Badge"
wifi_preference = false

[entry]
class = "EchtASketch"

[metadata]
author = "Jimmu"
license	= "MIT"
url = "https://github.com/jimmu/badge-a-sketch/"
description = "Frustrating drawing tool. Shake upside down to erase."
version = "0.1"
